sudo: false # only for faster builds
script:
  - clang -coverage -O0 pattern.c -o pattern
  - ./pattern
  - gcov pattern.c
  - clang -coverage -O0 triangle_pattern.c -o triangle_pattern
  - ./triangle_pattern
  - gcov triangle_pattern.c
   - clang -coverage -O0 fact_manju.c -o fact_manju
  - ./fact_manju
  - gcov fact_manju.c

after_success:
  - bash <(curl -s https://codecov.io/bash)

