matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc
      script:  
        - gcc -o manjunath fact_manju.c
        - ./manjunath
        - gcc -o chandrashekar pattern.c
        - ./chandrashekar
        - gcc -o deekshith triangle_pattern.c
        - ./deekshith
