matrix:
  include:    
    - language: c  
      sudo: false # only for faster builds  
      compiler:
        - clang
        - gcc
      script:  
        - gcc -o chandu fact_manju.c
        - ./chandu
        - gcc -o pattar pattern.c
        - ./pattar
        - gcc -o peace triangle_pattern.c
        - ./peace
